# Generated by Django 2.2.7 on 2019-12-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DB_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.CharField(max_length=255)),
                ('Account_type', models.IntegerField()),
                ('Account_balance', models.IntegerField()),
                ('Account_limit', models.IntegerField()),
                ('Account_payday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Value', models.IntegerField()),
                ('Transaction_Date', models.DateField(auto_now=True)),
                ('Transaction_Category', models.CharField(max_length=255)),
                ('Transaction_Account', models.CharField(max_length=255)),
            ],
        ),
    ]
