# Generated by Django 2.2.5 on 2019-12-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.CharField(max_length=255)),
                ('Account_Dayfinsh', models.IntegerField(blank=True, null=True)),
                ('Account_type', models.IntegerField(choices=[(1, 'Wallet'), (2, 'Account'), (3, 'CreditCar'), (4, 'Account With Limit')])),
                ('Account_balance', models.IntegerField()),
                ('Account_limit', models.IntegerField(blank=True, null=True)),
                ('Account_payday', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(max_length=255)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Do_dogs_have_money_Website.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Value', models.IntegerField()),
                ('Transaction_Date', models.DateField()),
                ('Transaction_texte', models.CharField(blank=True, max_length=500, null=True)),
                ('Transaction_Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Do_dogs_have_money_Website.Accounts')),
                ('Transaction_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Do_dogs_have_money_Website.Category')),
            ],
        ),
    ]
