# Generated by Django 2.2.7 on 2019-12-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Do_dogs_have_money_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Do_dogs_have_money_Website.DB_Accounts'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Do_dogs_have_money_Website.Category'),
        ),
    ]
